# Generated by Django 4.2.16 on 2024-11-24 14:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_list',
            field=models.JSONField(default=accounts.models.User.default_product_list),
        ),
    ]
